-- 002_seed_questions.sql
-- ESL Grammar Games — Seed question bank (70 questions)
-- Maps existing in-memory question bank to the questions table.

insert into questions (id, book_level, topic, stem, options, correct_index, difficulty, source, validated, published_at) values
  (gen_random_uuid(), 'red',  'present-simple',    'Fill in the blank: "She _____ to school every day."',              '["go","goes","going","gone"]'::jsonb,        1, 2, 'seed', true, now()),
  (gen_random_uuid(), 'red',  'present-simple',    'Choose the correct sentence:',                                     '["He don''t like it.","He doesn''t likes it.","He doesn''t like it.","He not like it."]'::jsonb, 2, 2, 'seed', true, now()),
  (gen_random_uuid(), 'red',  'present-simple',    '"They _____ football every weekend."',                            '["plays","play","playing","is play"]'::jsonb, 1, 2, 'seed', true, now()),
  (gen_random_uuid(), 'red',  'present-simple',    '"My mother _____ dinner at 6 o''clock."',                        '["cook","cooks","cooking","is cook"]'::jsonb, 1, 2, 'seed', true, now()),
  (gen_random_uuid(), 'red',  'present-simple',    'Which is correct?',                                               '["I doesn''t like ice cream.","I don''t likes ice cream.","I don''t like ice cream.","I not like ice cream."]'::jsonb, 2, 2, 'seed', true, now()),
  (gen_random_uuid(), 'red',  'past-tense',         'What is the past tense of "go"?',                                '["goed","went","going","gone"]'::jsonb,      1, 2, 'seed', true, now()),
  (gen_random_uuid(), 'red',  'past-tense',         'What is the past tense of "eat"?',                               '["eated","eat","ate","eaten"]'::jsonb,       2, 2, 'seed', true, now()),
  (gen_random_uuid(), 'red',  'past-tense',         '"Yesterday, I _____ a book."',                                  '["read","reads","reading","readed"]'::jsonb, 0, 2, 'seed', true, now()),
  (gen_random_uuid(), 'red',  'past-tense',         'What is the past tense of "play"?',                              '["play","plays","played","playing"]'::jsonb, 2, 2, 'seed', true, now()),
  (gen_random_uuid(), 'red',  'past-tense',         '"She _____ her homework last night."',                           '["finish","finishes","finished","finishing"]'::jsonb, 2, 2, 'seed', true, now()),
  (gen_random_uuid(), 'red',  'past-tense',         'What is the past tense of "see"?',                               '["seed","saw","seen","seeing"]'::jsonb,      1, 2, 'seed', true, now()),
  (gen_random_uuid(), 'red',  'plurals',            'Choose the correct plural form of "child":',                     '["childs","childes","children","chields"]'::jsonb, 2, 2, 'seed', true, now()),
  (gen_random_uuid(), 'red',  'plurals',            'What is the plural of "box"?',                                   '["boxs","boxes","boxies","boxen"]'::jsonb,   1, 2, 'seed', true, now()),
  (gen_random_uuid(), 'red',  'plurals',            'What is the plural of "baby"?',                                  '["babys","babyes","babies","babyies"]'::jsonb, 2, 2, 'seed', true, now()),
  (gen_random_uuid(), 'red',  'plurals',            'What is the plural of "tooth"?',                                 '["tooths","teeth","toothes","teeths"]'::jsonb, 1, 2, 'seed', true, now()),
  (gen_random_uuid(), 'red',  'plurals',            'What is the plural of "fish"?',                                  '["fishs","fishes","fish","fishies"]'::jsonb, 2, 2, 'seed', true, now()),
  (gen_random_uuid(), 'red',  'articles',           'Which article is correct: "_____ honest man"?',                 '["a","an","the","no article"]'::jsonb,       1, 2, 'seed', true, now()),
  (gen_random_uuid(), 'red',  'articles',           '"I saw _____ elephant at the zoo."',                             '["a","an","the","no article"]'::jsonb,       1, 2, 'seed', true, now()),
  (gen_random_uuid(), 'red',  'articles',           '"_____ sun rises in the east."',                                '["A","An","The","No article"]'::jsonb,       2, 2, 'seed', true, now()),
  (gen_random_uuid(), 'red',  'articles',           '"She is _____ university student."',                             '["a","an","the","no article"]'::jsonb,       0, 2, 'seed', true, now()),
  (gen_random_uuid(), 'blue', 'prepositions',       'Which is correct?',                                              '["I am good at maths.","I am good in maths.","I am good on maths.","I am good at mathses."]'::jsonb, 0, 3, 'seed', true, now()),
  (gen_random_uuid(), 'red',  'prepositions',       '"The cat is _____ the table."',                                 '["in","on","at","to"]'::jsonb,               1, 2, 'seed', true, now()),
  (gen_random_uuid(), 'red',  'prepositions',       '"We arrived _____ the airport at 8am."',                        '["in","on","at","to"]'::jsonb,               2, 2, 'seed', true, now()),
  (gen_random_uuid(), 'blue', 'prepositions',       '"She walked _____ the park."',                                  '["in","on","at","through"]'::jsonb,          3, 3, 'seed', true, now()),
  (gen_random_uuid(), 'red',  'prepositions',       '"The book is _____ the bag."',                                  '["on","at","in","by"]'::jsonb,               2, 2, 'seed', true, now()),
  (gen_random_uuid(), 'red',  'antonyms',           'What is the opposite of "early"?',                               '["soon","late","first","last"]'::jsonb,      1, 2, 'seed', true, now()),
  (gen_random_uuid(), 'red',  'antonyms',           'What is the opposite of "happy"?',                               '["glad","angry","sad","tired"]'::jsonb,      2, 2, 'seed', true, now()),
  (gen_random_uuid(), 'red',  'antonyms',           'What is the opposite of "big"?',                                 '["huge","small","tall","long"]'::jsonb,      1, 2, 'seed', true, now()),
  (gen_random_uuid(), 'red',  'antonyms',           'What is the opposite of "hot"?',                                 '["warm","cool","cold","wet"]'::jsonb,        2, 2, 'seed', true, now()),
  (gen_random_uuid(), 'red',  'antonyms',           'What is the opposite of "fast"?',                                '["quick","slow","hard","soft"]'::jsonb,      1, 2, 'seed', true, now()),
  (gen_random_uuid(), 'blue', 'vocabulary',         'What does "mutton" mean?',                                       '["Lamb","Beef","Pork","Chicken"]'::jsonb,    0, 3, 'seed', true, now()),
  (gen_random_uuid(), 'blue', 'vocabulary',         'What does "brave" mean?',                                        '["Scared","Not afraid","Tired","Lazy"]'::jsonb, 1, 3, 'seed', true, now()),
  (gen_random_uuid(), 'blue', 'vocabulary',         'Which word means "a place to borrow books"?',                    '["Museum","Library","Hospital","Station"]'::jsonb, 1, 3, 'seed', true, now()),
  (gen_random_uuid(), 'blue', 'present-continuous', '"Look! The baby _____ ."',                                      '["cry","cries","is crying","cried"]'::jsonb, 2, 3, 'seed', true, now()),
  (gen_random_uuid(), 'blue', 'present-continuous', '"They _____ football right now."',                              '["play","plays","are playing","played"]'::jsonb, 2, 3, 'seed', true, now()),
  (gen_random_uuid(), 'blue', 'present-continuous', '"I _____ my homework at the moment."',                          '["do","does","am doing","did"]'::jsonb,       2, 3, 'seed', true, now()),
  (gen_random_uuid(), 'blue', 'present-continuous', 'Which sentence is correct?',                                     '["She is cook dinner.","She is cooking dinner.","She are cooking dinner.","She cooking dinner."]'::jsonb, 1, 3, 'seed', true, now()),
  (gen_random_uuid(), 'blue', 'comparatives',       '"An elephant is _____ than a mouse."',                           '["big","bigger","biggest","more big"]'::jsonb, 1, 3, 'seed', true, now()),
  (gen_random_uuid(), 'blue', 'comparatives',       '"She is the _____ girl in the class."',                          '["tall","taller","tallest","most tall"]'::jsonb, 2, 3, 'seed', true, now()),
  (gen_random_uuid(), 'blue', 'comparatives',       '"This book is _____ than that one."',                            '["interesting","more interesting","most interesting","interestinger"]'::jsonb, 1, 3, 'seed', true, now()),
  (gen_random_uuid(), 'blue', 'comparatives',       '"Today is _____ day of the year."',                              '["hot","hotter","hottest","the hottest"]'::jsonb, 3, 3, 'seed', true, now()),
  (gen_random_uuid(), 'blue', 'adverbs',            '"She sings _____ ."',                                            '["beautiful","beautifully","beauty","beautifull"]'::jsonb, 1, 3, 'seed', true, now()),
  (gen_random_uuid(), 'blue', 'adverbs',            '"He drives _____ ."',                                           '["careful","carefully","care","caring"]'::jsonb, 1, 3, 'seed', true, now()),
  (gen_random_uuid(), 'blue', 'adverbs',            'Which is correct?',                                              '["I did good on the test.","I did well on the test.","I did nicely on the test.","I did fine on the test."]'::jsonb, 1, 3, 'seed', true, now()),
  (gen_random_uuid(), 'blue', 'questions',          '"_____ you like chocolate?"',                                   '["Do","Does","Are","Is"]'::jsonb,            0, 3, 'seed', true, now()),
  (gen_random_uuid(), 'blue', 'questions',          '"_____ she go to school by bus?"',                              '["Do","Does","Is","Are"]'::jsonb,            1, 3, 'seed', true, now()),
  (gen_random_uuid(), 'blue', 'questions',          '"Where _____ you born?"',                                       '["do","does","was","is"]'::jsonb,            2, 3, 'seed', true, now()),
  (gen_random_uuid(), 'red',  'questions',          '"_____ is your favourite colour?"',                             '["Who","Where","What","When"]'::jsonb,       2, 2, 'seed', true, now()),
  (gen_random_uuid(), 'blue', 'modals',             '"You _____ wear a seatbelt in the car."',                        '["can","should","may","would"]'::jsonb,      1, 3, 'seed', true, now()),
  (gen_random_uuid(), 'blue', 'modals',             '"_____ I borrow your pen?"',                                    '["Must","Should","May","Would"]'::jsonb,     2, 3, 'seed', true, now()),
  (gen_random_uuid(), 'blue', 'modals',             '"She _____ swim when she was five."',                            '["can","could","may","must"]'::jsonb,        1, 3, 'seed', true, now()),
  (gen_random_uuid(), 'blue', 'modals',             '"You _____ eat too much sugar."',                                '["shouldn''t","couldn''t","wouldn''t","mustn''t"]'::jsonb, 0, 3, 'seed', true, now()),
  (gen_random_uuid(), 'green', 'past-continuous',   '"I _____ TV when the phone rang."',                             '["watch","watched","was watching","am watching"]'::jsonb, 2, 4, 'seed', true, now()),
  (gen_random_uuid(), 'green', 'past-continuous',   '"They _____ in the park when it started to rain."',             '["walk","walked","were walking","are walking"]'::jsonb, 2, 4, 'seed', true, now()),
  (gen_random_uuid(), 'blue', 'future',             '"I _____ visit my grandma tomorrow."',                          '["will","am","was","do"]'::jsonb,            0, 3, 'seed', true, now()),
  (gen_random_uuid(), 'blue', 'future',             '"She _____ going to travel next month."',                       '["is","are","was","will"]'::jsonb,           0, 3, 'seed', true, now()),
  (gen_random_uuid(), 'green', 'subjunctive',       'Fill in the blank: "If I _____ rich, I would travel the world."', '["am","was","were","be"]'::jsonb,            2, 4, 'seed', true, now()),
  (gen_random_uuid(), 'green', 'conditionals',      '"If it rains, I _____ stay at home."',                          '["will","would","can","am"]'::jsonb,         0, 4, 'seed', true, now()),
  (gen_random_uuid(), 'green', 'conditionals',      '"If I _____ you, I would study harder."',                        '["am","was","were","be"]'::jsonb,            2, 4, 'seed', true, now()),
  (gen_random_uuid(), 'green', 'past-perfect',      '"By the time she arrived, we _____ dinner."',                   '["have eaten","had eaten","has eaten","were eating"]'::jsonb, 1, 4, 'seed', true, now()),
  (gen_random_uuid(), 'green', 'past-perfect',      '"He _____ already left when I called."',                         '["has","had","have","was"]'::jsonb,          1, 4, 'seed', true, now()),
  (gen_random_uuid(), 'green', 'passive',           '"The cake _____ by my mother."',                                '["was made","is made","made","did make"]'::jsonb, 0, 4, 'seed', true, now()),
  (gen_random_uuid(), 'green', 'passive',           '"English _____ in many countries."',                             '["speaks","is spoke","is spoken","was speak"]'::jsonb, 2, 4, 'seed', true, now()),
  (gen_random_uuid(), 'green', 'passive',           '"The homework _____ by the students yesterday."',               '["was finished","is finished","finished","did finish"]'::jsonb, 0, 4, 'seed', true, now()),
  (gen_random_uuid(), 'blue', 'conjunctions',       '"I was tired, _____ I went to bed early."',                     '["but","so","because","and"]'::jsonb,        1, 3, 'seed', true, now()),
  (gen_random_uuid(), 'blue', 'conjunctions',       '"She likes cats _____ she is allergic to them."',               '["and","so","but","because"]'::jsonb,        2, 3, 'seed', true, now()),
  (gen_random_uuid(), 'blue', 'conjunctions',       '"I stayed at home _____ it was raining."',                      '["so","but","and","because"]'::jsonb,        3, 3, 'seed', true, now()),
  (gen_random_uuid(), 'red',  'pronouns',           '"_____ is a good student." (talking about a boy)',              '["She","He","It","They"]'::jsonb,            1, 2, 'seed', true, now()),
  (gen_random_uuid(), 'red',  'pronouns',           '"The books are on the table. _____ are mine."',                 '["It","He","They","She"]'::jsonb,            2, 2, 'seed', true, now()),
  (gen_random_uuid(), 'red',  'pronouns',           '"This is _____ book." (belonging to me)',                       '["I","me","my","mine"]'::jsonb,              2, 2, 'seed', true, now());
